### ISSUE TITLE
Pixel 4?

### ISSUE THREAD

**Issue by Manouchehri** [Peter-Easton/android-debug-cable-howto#4]
Has anyone got their debug cable to work with a Pixel 4? Having issues with mine at the moment, and sadly don't have a Pixel 2/3 to verify if my wiring is working.

**Comment by Manouchehri** [comment]
User error with my serial adapter, forgot that this one needed VCC. Used a different adapter and it works! :D

**Comment by pingwuu** [comment]
> User error with my serial adapter, forgot that this one needed VCC. Used a different adapter and it works! :D
@Manouchehri, Which PIN is for VCC? My adapter for Pixel 3 RX is worked, but TX is not worked, I did not input anything on minicom console.
Thanks.

**Comment by samueldr** [comment]
"needing VCC" was about the serial adapter. Their serial adapter needed to be powered. They used a different adapater.

(Further answer to @pingwuu in #7)
